#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Game.Config.Contracts;
using Game.Config.Editor.Types;
using UnityEditor;
using UnityEngine;

namespace Game.Config.Editor.Generator
{
    /// <summary>代码生成侧：确保输出目录存在，并写入 CI 用 JSON 摘要与人读 txt。</summary>
    public sealed class ConfigCodeGenerator
    {
        private const string GeneratedPath = "Assets/Game/Config/Generated";
        private const string GeneratedTablesPath = "Assets/Game/Config/Generated/Tables";

        /// <summary>若不存在则创建 <c>Assets/Game/Config/Generated</c> 目录。</summary>
        public void EnsureGeneratedFolder()
        {
            if (!AssetDatabase.IsValidFolder("Assets/Game/Config"))
            {
                AssetDatabase.CreateFolder("Assets/Game", "Config");
            }

            if (!AssetDatabase.IsValidFolder(GeneratedPath))
            {
                AssetDatabase.CreateFolder("Assets/Game/Config", "Generated");
            }

            if (!AssetDatabase.IsValidFolder(GeneratedTablesPath))
            {
                AssetDatabase.CreateFolder("Assets/Game/Config/Generated", "Tables");
            }
        }

        /// <summary>写入 <c>generation-summary.json</c>，供 CI 或脚本对比生成是否变化。</summary>
        public void WriteCiSummaryJson(ConfigGenerationSummary summary)
        {
            EnsureGeneratedFolder();
            var json = JsonUtility.ToJson(summary, prettyPrint: true);
            var filePath = $"{GeneratedPath}/generation-summary.json";
            File.WriteAllText(filePath, json);
        }

        /// <summary>写入一行文本摘要，便于人工快速确认管线已跑。</summary>
        public void GenerateSummaryStub(bool validationSuccess)
        {
            var filePath = $"{GeneratedPath}/GeneratedSummary.txt";
            var line = validationSuccess
                ? "Config generation OK (see generation-summary.json)."
                : "Config generation validation failed (see generation-summary.json).";
            File.WriteAllText(filePath, line);
        }

        /// <summary>
        /// 根据批次表结构生成 C# 类文件（每张表一个 *.gen.cs）。
        /// </summary>
        public void GenerateTableClasses(ConfigValidationBatch batch)
        {
            if (batch == null)
            {
                return;
            }

            EnsureGeneratedFolder();

            foreach (var table in batch.Tables)
            {
                if (table == null || string.IsNullOrWhiteSpace(table.SheetName) || table.Columns.Count == 0)
                {
                    continue;
                }

                var tableType = ToTypeName(table.SheetName) + "ConfigTable";
                var code = BuildTableCode(table);
                var fileName = $"{tableType}.gen.cs";
                var path = $"{GeneratedTablesPath}/{fileName}";

                // Do not generate duplicate type when a hand-written/generated stable class already exists.
                var stablePath = $"{GeneratedPath}/{tableType}.cs";
                if (AssetDatabase.LoadAssetAtPath<MonoScript>(stablePath) != null)
                {
                    var staleGenerated = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                    if (staleGenerated != null)
                    {
                        AssetDatabase.DeleteAsset(path);
                    }

                    continue;
                }

                File.WriteAllText(path, code, Encoding.UTF8);
            }

            AssetDatabase.Refresh();
        }

        private static string BuildTableCode(ConfigValidationInput table)
        {
            var tableType = ToTypeName(table.SheetName) + "ConfigTable";
            var itemType = ToTypeName(table.SheetName) + "ConfigItem";

            var hasTypeRow = table.ColumnTypeTokens.Count == table.Columns.Count && table.ColumnTypeTokens.Count > 0;
            var idIndex = table.Columns.FindIndex(c => string.Equals(c, "Id", StringComparison.OrdinalIgnoreCase));
            var hasIntId = false;
            if (idIndex >= 0 && hasTypeRow)
            {
                hasIntId = FieldTypeParser.TryParseFieldType(
                               table.ColumnTypeTokens[idIndex],
                               ConfigPipelineOptions.TreatUnknownTypesAsEnum,
                               out var desc,
                               out _)
                           && desc.Kind == BuiltinFieldKind.Int;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Config table class generated by ConfigCodeGenerator.");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Game.Config.Contracts;");
            if (hasTypeRow && UsesSyntheticEnum(table))
            {
                sb.AppendLine("using Game.Config.Generated.Enums;");
            }

            sb.AppendLine();
            sb.AppendLine("namespace Game.Config.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    [CreateAssetMenu(menuName = \"Game/Config/{tableType}\", fileName = \"{tableType}\")]");
            if (hasIntId)
            {
                sb.AppendLine($"    public sealed class {tableType} : ScriptableObject, IConfigTable<int, {itemType}>");
            }
            else
            {
                sb.AppendLine($"    public sealed class {tableType} : ScriptableObject");
            }

            sb.AppendLine("    {");
            sb.AppendLine($"        [SerializeField] private List<{itemType}> items = new List<{itemType}>();");
            if (hasIntId)
            {
                sb.AppendLine($"        private Dictionary<int, {itemType}> _index;");
                sb.AppendLine();
                sb.AppendLine($"        public bool TryGet(int key, out {itemType} item)");
                sb.AppendLine("        {");
                sb.AppendLine("            EnsureIndex();");
                sb.AppendLine("            return _index.TryGetValue(key, out item);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public {itemType} Get(int key)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (TryGet(key, out var item)) return item;");
                sb.AppendLine($"            throw new KeyNotFoundException(\"{tableType} key not found: \" + key);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public IReadOnlyList<{itemType}> GetAll()");
                sb.AppendLine("        {");
                sb.AppendLine("            return items;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        private void EnsureIndex()");
                sb.AppendLine("        {");
                sb.AppendLine("            if (_index != null) return;");
                sb.AppendLine($"            _index = new Dictionary<int, {itemType}>();");
                sb.AppendLine("            foreach (var item in items)");
                sb.AppendLine("            {");
                sb.AppendLine("                _index[item.Id] = item;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine();
                sb.AppendLine($"        public IReadOnlyList<{itemType}> GetAll()");
                sb.AppendLine("        {");
                sb.AppendLine("            return items;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {itemType}");
            sb.AppendLine("    {");
            for (var i = 0; i < table.Columns.Count; i++)
            {
                var col = table.Columns[i];
                var fieldName = ToFieldName(col);
                var csType = ResolveFieldType(table, i);
                sb.AppendLine($"        public {csType} {fieldName};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static bool UsesSyntheticEnum(ConfigValidationInput table)
        {
            for (var i = 0; i < table.ColumnTypeTokens.Count; i++)
            {
                if (FieldTypeParser.TryParseFieldType(
                        table.ColumnTypeTokens[i],
                        ConfigPipelineOptions.TreatUnknownTypesAsEnum,
                        out var desc,
                        out _) && desc.IsSyntheticEnum)
                {
                    return true;
                }
            }

            return false;
        }

        private static string ResolveFieldType(ConfigValidationInput table, int index)
        {
            if (table.ColumnTypeTokens.Count != table.Columns.Count)
            {
                return GuessLegacyType(table.Columns[index]);
            }

            var token = table.ColumnTypeTokens[index];
            if (!FieldTypeParser.TryParseFieldType(
                    token,
                    ConfigPipelineOptions.TreatUnknownTypesAsEnum,
                    out var desc,
                    out _))
            {
                return "string";
            }

            switch (desc.Kind)
            {
                case BuiltinFieldKind.Int:
                    return "int";
                case BuiltinFieldKind.Float:
                    return "float";
                case BuiltinFieldKind.Double:
                    return "double";
                case BuiltinFieldKind.Long:
                    return "long";
                case BuiltinFieldKind.String:
                    return "string";
                case BuiltinFieldKind.Vector2:
                    return "Vector2";
                case BuiltinFieldKind.Vector3:
                    return "Vector3";
                case BuiltinFieldKind.Vector4:
                    return "Vector4";
                case BuiltinFieldKind.Rect:
                    return "Rect";
                case BuiltinFieldKind.Color:
                    return "Color";
                case BuiltinFieldKind.IntArray:
                    return "int[]";
                case BuiltinFieldKind.LongArray:
                    return "long[]";
                case BuiltinFieldKind.FloatArray:
                    return "float[]";
                case BuiltinFieldKind.DoubleArray:
                    return "double[]";
                case BuiltinFieldKind.StringArray:
                    return "string[]";
                case BuiltinFieldKind.SyntheticEnum:
                    return desc.SyntheticEnumName;
                default:
                    return "string";
            }
        }

        private static string GuessLegacyType(string column)
        {
            if (string.Equals(column, "Id", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(column, "Value", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(column, "AttrId", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(column, "BuffId", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(column, "SkillId", StringComparison.OrdinalIgnoreCase))
            {
                return "int";
            }

            return "string";
        }

        private static string ToTypeName(string raw)
        {
            var parts = raw.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var p in parts)
            {
                if (p.Length == 0) continue;
                var first = p[0];
                if (char.IsLetter(first) || first == '_')
                {
                    sb.Append(char.ToUpperInvariant(first));
                }
                else
                {
                    sb.Append('_');
                    sb.Append(first);
                }

                if (p.Length > 1)
                {
                    sb.Append(p.Substring(1));
                }
            }

            if (sb.Length == 0)
            {
                return "Unnamed";
            }

            return SanitizeIdentifier(sb.ToString());
        }

        private static string ToFieldName(string raw)
        {
            var name = ToTypeName(raw);
            if (string.Equals(name, "String", StringComparison.Ordinal))
            {
                name = "StringValue";
            }

            return SanitizeIdentifier(name);
        }

        private static string SanitizeIdentifier(string raw)
        {
            var sb = new StringBuilder();
            for (var i = 0; i < raw.Length; i++)
            {
                var ch = raw[i];
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    sb.Append(ch);
                }
                else
                {
                    sb.Append('_');
                }
            }

            if (sb.Length == 0)
            {
                return "_";
            }

            if (char.IsDigit(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }
    }
}
#endif
