#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using Game.Config.Contracts;
using Game.Config.Editor.Types;
using UnityEditor;

namespace Game.Config.Editor.Generator
{
    /// <summary>
    /// 当开启 <see cref="ConfigPipelineOptions.TreatUnknownTypesAsEnum"/> 时，为类型行中的合成枚举生成代码文件。
    /// </summary>
    public static class SyntheticEnumGenerator
    {
        private const string OutputDir = "Assets/Game/Config/Generated/Enums";

        public static void GenerateForBatch(ConfigValidationBatch batch)
        {
            if (!ConfigPipelineOptions.TreatUnknownTypesAsEnum || batch == null)
            {
                return;
            }

            var enumToRawValues = new Dictionary<string, HashSet<string>>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var table in batch.Tables)
            {
                Collect(table, enumToRawValues);
            }

            if (enumToRawValues.Count == 0)
            {
                return;
            }

            EnsureFolder();
            foreach (var kv in enumToRawValues)
            {
                WriteEnumFile(kv.Key, kv.Value);
            }

            AssetDatabase.Refresh();
        }

        private static void Collect(ConfigValidationInput table, Dictionary<string, HashSet<string>> map)
        {
            if (table.ColumnTypeTokens.Count != table.Columns.Count)
            {
                return;
            }

            for (var c = 0; c < table.Columns.Count; c++)
            {
                if (!FieldTypeParser.TryParseFieldType(
                        table.ColumnTypeTokens[c],
                        ConfigPipelineOptions.TreatUnknownTypesAsEnum,
                        out var desc,
                        out _))
                {
                    continue;
                }

                if (!desc.IsSyntheticEnum)
                {
                    continue;
                }

                var enumName = desc.SyntheticEnumName;
                if (!map.TryGetValue(enumName, out var set))
                {
                    set = new HashSet<string>(System.StringComparer.Ordinal);
                    map[enumName] = set;
                }

                var col = table.Columns[c];
                foreach (var row in table.Rows)
                {
                    if (!row.TryGetValue(col, out var v))
                    {
                        continue;
                    }

                    if (string.IsNullOrWhiteSpace(v))
                    {
                        continue;
                    }

                    set.Add(v.Trim());
                }
            }
        }

        private static void EnsureFolder()
        {
            if (!AssetDatabase.IsValidFolder("Assets/Game/Config/Generated"))
            {
                AssetDatabase.CreateFolder("Assets/Game/Config", "Generated");
            }

            if (!AssetDatabase.IsValidFolder(OutputDir))
            {
                AssetDatabase.CreateFolder("Assets/Game/Config/Generated", "Enums");
            }
        }

        private static void WriteEnumFile(string enumName, HashSet<string> rawValues)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Synthetic enum from config type row.");
            sb.AppendLine("namespace Game.Config.Generated.Enums");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");

            var used = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var raw in rawValues)
            {
                var member = SyntheticEnumNaming.AllocateMemberName(raw, used);
                sb.AppendLine($"        {member}, // raw: {EscapeComment(raw)}");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var path = $"{OutputDir}/{enumName}.gen.cs";
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        }

        private static string EscapeComment(string raw)
        {
            return raw.Replace("\r", "").Replace("\n", " ").Replace("*/", "* /");
        }

    }
}
#endif
